package bob.colbaskin.cookly.common.design_system.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class AppColors(
    val background: Color,
    val accentColor: Color,
    val cardBackground: Color,
    val text: Color,
    val invertedText: Color,
    val tertiaryText: Color,
    val likeColor: Color,
    val flameColor: Color,
    val statsCardBackground: Color,
    val secondaryCardBackground: Color,
    val strokeColor: Color,
    val glassColor: Color,
    val outlinedStatsSurface: Color,
    val filledStatsSurface: Color,
    val mealCardBorder: Color,
    val bottomBarIcon: Color,
    val onErrorContainer: Color,
    val errorContainer: Color,
    val secondAccentColor: Color,
    val selectedPreferences: Color,
    val secondaryText: Color,
    val quickCategoryCardText: Color,
    val quickCategoryCardBackground: Color,
    val dishCardBackground: Color,
    val liquidBackground: Color,
    val addToCartColor: Color,
    val accentSecondSurface: Color,
    val ingredientSurface: Color
)

val localColors = staticCompositionLocalOf { lightColorsScheme }

val darkColorsScheme = AppColors(
    background = Color(0xFF10100F),
    accentColor = Color(0xFFE59830),
    secondAccentColor = Color(0xFF8FB96A),
    cardBackground = Color(0xFF1B1A18),
    secondaryCardBackground = Color(0xFF24221F),
    statsCardBackground = Color(0xFF211F1D),
    dishCardBackground = Color(0xFF181715),
    text = Color(0xFFF5F1EA),
    invertedText = Color(0xFF121212),
    tertiaryText = Color(0xFF8F8A83),
    secondaryText = Color(0xFFB8B0A6),
    likeColor = Color(0xFFFF5C64),
    flameColor = Color(0xFFFF6A3D),
    strokeColor = Color(0xFF34312D),
    glassColor = Color(0x331F1D1A),
    outlinedStatsSurface = Color(0xFF25231F),
    filledStatsSurface = Color(0xFF2E2A25),
    mealCardBorder = Color(0xFF4A453F),
    bottomBarIcon = Color(0xFF8A9BB0),
    onErrorContainer = Color(0xFFFFDAD6),
    errorContainer = Color(0xFF5D1A1A),
    selectedPreferences = Color(0xFF314729),
    quickCategoryCardText = Color(0xFFF7F2EA),
    quickCategoryCardBackground = Color(0xFF24211D),
    liquidBackground = Color(0xFF3A332B),
    addToCartColor = Color(0xFFE59830),
    accentSecondSurface = Color(0xFF4A3D18),
    ingredientSurface = Color(0xFF202C29),
)

val lightColorsScheme = AppColors(
    background = Color(0xFFFFFFFF),
    accentColor = Color(0xFFE59830),
    cardBackground = Color(0xFF1C1B1C),
    text = Color(0xFF000000),
    invertedText = Color(0xFFFFFFFF),
    tertiaryText = Color(0xFF767676),
    likeColor = Color(0xFFFF5356),
    flameColor = Color(0xFFFF0000),
    statsCardBackground = Color(0xFFEDEDED),
    secondaryCardBackground = Color(0xFFF4F4F4),
    strokeColor = Color(0xFFE2E2E2),
    glassColor = Color(0xFFFFFFFF),
    outlinedStatsSurface = Color(0xFFF3F3F3),
    filledStatsSurface = Color(0xFFFFFFFF),
    mealCardBorder = Color(0xFF818181),
    bottomBarIcon = Color(0xFF9DB2CE),
    onErrorContainer = Color.White,
    errorContainer = Color.Red,
    secondAccentColor = Color(0xFF6F9448),
    selectedPreferences = Color(0xFFC7E5A6),
    secondaryText = Color(0xFFB9B9B9),
    quickCategoryCardText = Color(0xFFFFFFFF),
    quickCategoryCardBackground = Color(0xFF000000),
    dishCardBackground = Color(0xFFFBFBFB),
    liquidBackground = Color(0xFFA1968A),
    addToCartColor = Color(0xFF3D3D3D),
    accentSecondSurface = Color(0xFFFFE27E),
    ingredientSurface = Color(0xFFECF2F0),
)
